### PR TITLE
Pass binary file object to Tomli

### PR DESCRIPTION
**Pull request by hukkin**
Closes https://github.com/ikamensh/flynt/issues/119

### CODE REVIEW

**Comment by ikamensh** [comment]
Thanks for the PR. Can't reproduce the #119, I think the issue needs clarification as for the root cause / differences in the environment.

**Comment by hukkin** [comment]
The root cause is that they have `tomli==2.0.0` installed. Here's the Tomli changelog https://github.com/hukkin/tomli/blob/master/CHANGELOG.md#200

Text file objects as `tomli.load` input have been deprecated since July last year.

**Comment by ikamensh** [comment]
Ok so you're the author of tomli and I see that latest version on GH no longer has clause for non-bytes.

I actually liked the generality of 
```python
def load(fp: IO, *, parse_float: ParseFloat = float) -> Dict[str, Any]:
    """Parse TOML from a file object."""
    s = fp.read()
    if isinstance(s, bytes):
        s = s.decode()
    return loads(s, parse_float=parse_float)
```

But if you have decided to let this go (I hope not for performance of sparing one if statement :D ) then this PR needs to bump minimum version of `tomli`.

**Comment by hukkin** [comment]
> But if you have decided to let this go (I hope not for performance of sparing one if statement :D )

Yeah this decision was made because you need to do `open("conf.toml", encoding="utf-8", newline="")`. If you omit one of the two arguments you may get incorrect parse results. It is a footgun.

> then this PR needs to bump minimum version of tomli.

The current minimum version (1.1.0) is correct. That is the first version that supports binary file objects.

**Comment by ikamensh** [comment]
Good. thanks for explaining :)

**Pull request merged**
