### PR TITLE
tidied up a bunch of pylint warnings

### PR DESCRIPTION
**Pull request by marksmayo**
Newline issues
white space
simplified if/else cases
tidied imports

### CODE REVIEW

**Comment by marksmayo** [comment]
============================================================ 365 passed, 1 warning in 4.65s =============================================================

**Comment by ikamensh** [comment]
Hi, thanks for your PR.

Can you remove changes on `tests/integration/samples_in*` and `/expected_out*`? These are demo files to convert, not source code.

**Comment by marksmayo** [comment]
Hey, I get your logic as they're source, but all I did was add / tidy whitespace on them.  All tests still pass so I don't think they're affected as such? Is there another reason I'm missing?  More curious than anything, but just wanted to check first before I revert. Thanks!

**Comment by marksmayo** [comment]
All good, just wanted clarity.

I think I'll close the PR and try again.  I've been using flynt this week on a few projects and love how well it runs, but (as you mention) there are some that it doesn't handle that I've come across.  Ideally I'll raise some issues on it and maybe take a look myself too.

**Pull request closed without merging**
