### PR TITLE
pre-commit: Add bandit

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/PyCQA/bandit -- Would it be worthwhile to avoid [Bandit B307](https://bandit.readthedocs.io/en/1.7.4/blacklists/blacklist_calls.html#b307-eval)?
```
>> Issue: [B307:blacklist] Use of possibly insecure function - consider using safer ast.literal_eval.
   Severity: Medium   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   Location: ./flynt/test/test_process.py:446:11
   More Info: https://bandit.readthedocs.io/en/1.7.4/blacklists/blacklist_calls.html#b307-eval
```

### CODE REVIEW

**Comment by ikamensh** [comment]
The issue is in tests, I think it's not worth a change. Though maybe it's better to ignore tests completely for `bandit` and enable this check to verify it's not occurring in the user facing code.

**Comment by cclauss** [comment]
https://github.com/ikamensh/flynt/search?q=eval( says `eval(` is only happening on one test file.

**Comment by ikamensh** [comment]
Few considerations for this PR:

1. So the idea behind ignoring tests is that for future changes we will avoid any overhead of adding exceptions should non-secure code be used in test (I'm thinking it's harmless in tests). So I suggest ignoring tests for bandit, it must have some way to specify which files to check and not.
2. checking eval doesn't happen in production code is potentially valuable, so I would not disable this check. That's only possible if we ignore tests again.
3. Should CI run pre-commit to make sure what's on the main branch actually passes the checks?
4. Not sure if it's valuable to also include bandit in requirements-dev.txt given that pre-commit will anyhow not use the pip installed package. (not an action point if you agree)

**Comment by cclauss** [comment]
`bandit --exclude=./test --skip=B101 --recursive .`

**Comment by ikamensh** [comment]
Interestingly despite this including Run pre-commit in Actions change, I don't see the job in the list of checks on this run.

**Comment by cclauss** [comment]
Rebasing to master should fix that.

**Comment by cclauss** [comment]
https://pre-commit.ci is probably better for running pre-commit on pull requests than GitHub Actions.

**Pull request merged**
