### PR TITLE
Switch to PEP517 packaging with Hatch

### PR DESCRIPTION
**Pull request by akx**
[Hatch](https://hatch.pypa.io/latest/) is the PyPA-endorsed packaging solution.

This PR:

* switches `flynt` over to use Hatch (or rather its PEP517 package builder, `hatchling`) instead of `setup.py`.
* It also adds a GitHub Actions workflow to build the distribution package for each push, for e.g. automated testing.
* It removes the "duplicate" dev tools which are separately installed by `pre-commit` anyway from the dev dependencies.

### CODE REVIEW

**Comment by ikamensh** [comment]
Interesting, thanks for this proposal. I've never worked (or even heard yet) about Hatch, will need to read up and play around with it to see if I like it. Worst case I get to it around Christmas :)

**Comment by ikamensh** [comment]
If possible, could you split this into two PRs - one for pyproject.toml instead of requirements (I think setup.py works with pyproject.toml, if not disregard the whole proposal), and this PR would be only about moving to Hatch?

**Comment by akx** [comment]
The idea with Hatch etc. is that you don't need setup.py (e.g. there will be no project-specific possibly arbitrary code run) when creating packages. I think this should be an atomic change...

**Comment by ikamensh** [comment]
Ok, I will need to read up and test Hatch to decide.

**Comment by akx** [comment]
@ikamensh I suggest reading up on PEP517 builders in general, Hatch is just one implementation, but it's "first-party" in the sense that it's PyPA's (the Python Packaging Authority, the stewards of e.g. `setuptools` and `pip`) project :)

**Review by ikamensh — APPROVED** [review]
Tested it with alpha version deployment, all works. Thanks

**Pull request merged**
