### PR TITLE
Remove direct wrapping of pyupgrade

### PR DESCRIPTION
**Pull request by asottile**
As discussed in [this thread].

- `pyupgrade` (intentionally) has no programmatic api
- as agreed, I've implemented a run-on-folder version of pyupgrade:
    - `pip install pyupgrade-directory`
    - `pyupgrade-directory [options] [folder / file] ...`
    - for example: `pyupgrade-directory /tmp/flynt/{src,test} --py37-plus`

[this thread]: https://github.com/ikamensh/flynt/commit/698782d6ed14bb132e383dfb479b6e30d7f7f5c8#commitcomment-35693130

### CODE REVIEW

**Comment by ikamensh** [comment]
Hey @asottile, thanks a lot for agreeing to my requests. While extremely flattered by having a PyPI package just for myself created by you, I was wondering:
1) Why do you implicitly disagree with being able to call it on a folder being something useful on the mainline of pyupgrade? Don't you think flynt demonstrates that there are people who find this useful?
2) what is your maintenance plan of `pyupgrade-for-ikamensh`? if there is none, then it is as good as not having it - I can just use the current version of flynt forever (as it is using fixed version of pyupgrade).

**Comment by ikamensh** [comment]
As for --upgrade flag, lets remove it - it will be explicit and I will find out if any user will be actually missing this functionality.

**Comment by asottile** [comment]
1. I have a few write ups on this but getting it completely correct is difficult
2. It's a simple wrapper around `find` which proxies to `pyupgrade`, this allows you to upgrade `pyupgrade` without worry

**Comment by asottile** [comment]
Updated: removed `--upgrade` flag as well

**Comment by ikamensh** [comment]
I have tried the `pyupgrade-for-ikamensh` on windows, unfortunately here is all I got:
```
C:\Users\Ilya\flask (master -> origin)  
λ pyupgrade-for-ikamensh .              
                                        
FIND: Parameter format not correct      
C:\Users\Ilya\flask (master -> origin)  
λ cd ..                                 
                                        
C:\Users\Ilya                           
λ pyupgrade-for-ikamensh flask\         
                                        
C:\Users\Ilya                           
λ File not found - *.py                 
```

**Comment by asottile** [comment]
mmm yeah it's assuming gnu or bsd `find` is available -- I guess I can make it work for windows as well (didn't know you used windows)

**Comment by asottile** [comment]
New version (0.0.1) should support windows

**Comment by asottile** [comment]
@ikamensh did the new version work for you on windows?

**Comment by ikamensh** [comment]
@asottile Yes it worked. We have to come up with a better name though - not sure I can announce "use pyupgrade-for-ikamensh instead of --upgrade flag" with straight face 😐. I have announced scheduled deprecation in the meanwhile.

**Comment by asottile** [comment]
do you have any suggestions?

**Comment by ikamensh** [comment]
I think `pyupgrade-dir` would be intuitive naming.

**Comment by asottile** [comment]
I went with [pyupgrade-directory](https://pypi.org/project/pyupgrade-directory/) so there's no ambiguity -- I've also rebased to resolve the conflicts

**Comment by ikamensh** [comment]
Hey Anthony, thanks for publishing it with more friendly name. I have discovered that my warning message on --upgrade flag was actually not published on PyPI, which I fixed just now. Will continue here in a few weeks (hopefully abt. 2).

**Pull request merged**
