### PR TITLE
Test coverage for the CLI part

### PR DESCRIPTION
**Pull request by jonathangjertsen**
This can help ensure the CLI code is valid and that the output is as expected. The motivation for this PR is that I have another one coming up which adds a new argument, and I didn't have a good way to test it.

### CODE REVIEW

**Comment by jonathangjertsen** [comment]
Hm, not sure why the build is failing on 3.8/3.9...

**Comment by ikamensh** [comment]
Looks like this is at odds with the string concatenation feature (enabled only in py3.8+), let me know if debugging this will get too confusing :)

**Comment by jonathangjertsen** [comment]
The problem was that the test writes to `flynt.state`, which the other tests don't expect.

I added the minimal amount of code to work around this (an documented function to reset flynt.state which is only used by the tests).

If you think that's too hackish, another solution I had in mind is to put something like this in `flynt/src/__init__.py`

```Python

class _State(object):
    def __init__(self):
        self.reset()

    def reset():
        self.verbose = False
        ...

state = _State()
```

Let me know what you prefer

**Comment by ikamensh** [comment]
Ok as it is. Small styling note - since we don't support py2,  you don't need your classes to inherit from `object`, but that's not important enough for new revision, will change once I work with this file.

**Pull request merged**
